# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# ワークフローの名前
name: Node.js CI

# ワークフローのトリガー
on:
  # ブランチにpushされたとき
  push:
    branches: ["main"]
  # プルリクエストが作成されたとき
  pull_request:
    branches: ["main"]

# ワークフローのジョブ
jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest

    # ビルドジョブのストラテジー
    strategy:
      # ビルドジョブのマトリクス
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # サポートされているNode.jsのリリーススケジュールはhttps://nodejs.org/en/about/releases/

    # ビルドジョブのステップ
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
